### ISSUE TITLE
Create New Button component that can be used in the project 

### ISSUE THREAD

**Issue by yasirunilan** [yasirunilan/CareApp#1]
Try to create a custom Angular4 Button component that can be used in the project.

**Comment by sjais789** [comment]
can you give detail of the project?

**Comment by elias-garcia** [comment]
See my pull request 😃

**Comment by yasirunilan** [comment]
@sjais789  I updated the project description https://github.com/yasirunilan/CareApp . please refer to that. If you have any problems make a comment.

**Comment by yasirunilan** [comment]
closed from #2
